// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {

    //fibonacci series first n term
   var f=1;
   var s=2;
   arr = [1,2]
   i=2
   while (i!=n){
  
    fibo = f+s;
    arr.push(fibo)
    f=s
    s=fibo;
    i++;
   }
sum=0


arr.forEach(index => {
    if(index<=n&&index%2==0){
        sum+=index
    }
});
console.log(sum)

  }


fiboEvenSum(1000);